"""Generator: SchemaForge IR → JSON Schema.

Converts tables/columns into a JSON Schema document
with each table as a ``$defs`` entry and columns as properties.
"""

from __future__ import annotations

import json
from typing import Any

from ..ir import Column, ColumnType, Schema, Table
from ..type_config import EMPTY_CONFIG, TypeConfig

# JSON Schema 2020-12 draft
_JSON_SCHEMA_VERSION = "https://json-schema.org/draft/2020-12/schema"

# ColumnType → JSON Schema type + format
_TYPE_TO_JSON: dict[ColumnType, dict[str, Any]] = {
    ColumnType.STRING: {"type": "string"},
    ColumnType.TEXT: {"type": "string"},
    ColumnType.INTEGER: {"type": "integer"},
    ColumnType.FLOAT: {"type": "number"},
    ColumnType.DECIMAL: {"type": "number"},
    ColumnType.BOOLEAN: {"type": "boolean"},
    ColumnType.DATETIME: {"type": "string", "format": "date-time"},
    ColumnType.DATE: {"type": "string", "format": "date"},
    ColumnType.TIME: {"type": "string", "format": "time"},
    ColumnType.JSON: {"type": "object"},
    ColumnType.BLOB: {"type": "string", "contentEncoding": "base64"},
    ColumnType.UUID: {"type": "string", "format": "uuid"},
    ColumnType.ENUM: {"type": "string"},
    ColumnType.CUSTOM: {"type": "string"},
}


class JSONSchemaGenerator:
    """Convert Schema IR to a JSON Schema document."""

    def __init__(self, type_config: TypeConfig | None = None) -> None:
        """Initialize with optional custom type overrides.

        Args:
            type_config: Optional custom type mapping overrides.
        """
        self._type_config = type_config or EMPTY_CONFIG

    def generate(self, schema: Schema) -> str:
        """Generate a JSON Schema document from Schema IR.

        Args:
            schema: Schema IR with tables and enums.

        Returns:
            Pretty-printed JSON Schema string.
        """
        document: dict[str, Any] = {
            "$schema": _JSON_SCHEMA_VERSION,
            "$id": "schema.json",
            "title": "Schema",
            "description": "Generated by SchemaForge",
            "$defs": {},
        }

        for enum_type in schema.enums:
            enum_def = self._enum_to_def(enum_type, schema)
            document["$defs"][enum_type.name] = enum_def

        for table in schema.tables:
            defn = self._table_to_def(table)
            document["$defs"][table.name] = defn

        # If only one table, also add a root schema ref
        if len(schema.tables) == 1:
            document["$ref"] = f"#/$defs/{schema.tables[0].name}"

        return json.dumps(document, indent=2) + "\n"

    def _table_to_def(self, table: Table) -> dict[str, Any]:
        """Convert a Table IR to a JSON Schema definition.

        Args:
            table: The table to convert.

        Returns:
            JSON Schema object definition.
        """
        properties: dict[str, Any] = {}
        required: list[str] = []

        for col in table.columns:
            prop = self._column_to_prop(col)
            properties[col.name] = prop
            if not col.nullable:
                required.append(col.name)

        defn: dict[str, Any] = {
            "type": "object",
            "properties": properties,
        }

        if required:
            defn["required"] = required

        if table.comment:
            defn["description"] = table.comment

        return defn

    def _column_to_prop(self, col: Column) -> dict[str, Any]:
        """Convert a Column IR to a JSON Schema property.

        Args:
            col: The column to convert.

        Returns:
            JSON Schema property object.
        """
        prop: dict[str, Any] = {}

        # Resolve type — check type_config overrides first
        if self._type_config:
            overridden = self._type_config.get_override(col, "json_schema")
            if overridden:
                # If override is a JSON object (starts with '{'), parse it
                if overridden.startswith("{") and overridden.endswith("}"):
                    try:
                        import json as _json

                        prop = _json.loads(overridden)
                        return self._add_base_annotations(prop, col)
                    except (json.JSONDecodeError, ValueError):
                        pass
                prop["type"] = overridden
                return self._add_base_annotations(prop, col)

        # Default type mapping
        if col.type in _TYPE_TO_JSON:
            prop.update(_TYPE_TO_JSON[col.type])
        elif col.custom_type:
            prop["type"] = "string"
            prop["description_meta"] = f"custom: {col.custom_type}"
        else:
            prop["type"] = "string"

        # ENUM → list values
        if col.type == ColumnType.ENUM and "values" in col.type_args:
            prop["enum"] = col.type_args["values"]

        # STRING with length → maxLength
        if col.type == ColumnType.STRING and "length" in col.type_args:
            prop["maxLength"] = col.type_args["length"]

        # DECIMAL → minimum/maximum hints if precision/scale available
        if col.type == ColumnType.DECIMAL:
            prec = col.type_args.get("precision")
            scale = col.type_args.get("scale")
            if prec:
                max_val = 10 ** (prec - (scale or 0)) - 10 ** -(scale or 0)
                prop["maximum"] = max_val
            if scale:
                prop["multipleOf"] = 10**-(scale)

        return self._add_base_annotations(prop, col)

    def _add_base_annotations(
        self, prop: dict[str, Any], col: Column
    ) -> dict[str, Any]:
        """Add common annotations (description, default, comment) to a property."""
        if col.comment:
            prop["description"] = col.comment
        if col.default is not None:
            # Handle fn: defaults → skip (can't represent functions in JSON Schema)
            if isinstance(col.default, str) and col.default.startswith("fn:"):
                pass
            else:
                prop["default"] = col.default
        return prop

    def _enum_to_def(self, enum_type, schema: Schema) -> dict[str, Any]:
        """Convert an EnumType IR to a JSON Schema enum definition.

        Args:
            enum_type: The enum type to convert.
            schema: Full schema (for context).

        Returns:
            JSON Schema definition with enum values.
        """
        return {
            "type": "string",
            "enum": enum_type.values,
            "description": f"Enum: {', '.join(enum_type.values)}",
        }
