"""Generator: SchemaForge IR → Scala case class definitions.

Generates Scala case classes suitable for use with Doobie, Quill,
or Slick. Handles Option[T] for nullable columns.
"""

from __future__ import annotations

from ..ir import Column, ColumnType, Schema
from ._base import resolve_type


class ScalaGenerator:
    """Convert Schema IR to Scala case class definitions."""

    _TYPE_MAP: dict[ColumnType, str] = {
        ColumnType.STRING: "String",
        ColumnType.INTEGER: "Int",
        ColumnType.FLOAT: "Double",
        ColumnType.BOOLEAN: "Boolean",
        ColumnType.DATETIME: "Instant",
        ColumnType.DATE: "LocalDate",
        ColumnType.TIME: "LocalTime",
        ColumnType.TEXT: "String",
        ColumnType.BLOB: "Array[Byte]",
        ColumnType.JSON: "String",
        ColumnType.UUID: "UUID",
        ColumnType.ENUM: "String",
        ColumnType.DECIMAL: "BigDecimal",
    }

    def __init__(self, type_config=None):
        """Initialize generator with optional type config."""
        self.type_config = type_config

    def generate(self, schema: Schema) -> str:
        """Generate Scala case class definitions from schema IR."""
        parts: list[str] = [
            "// Auto-generated by SchemaForge",
            "// https://github.com/Coding-Dev-Tools/schemaforge",
            "",
            "import java.time.{Instant, LocalDate, LocalTime}",
            "import java.util.UUID",
            "import scala.math.BigDecimal",
            "",
        ]

        # Generate imports based on types used
        needed_imports: set[str] = set()
        for table in schema.tables:
            for col in table.columns:
                sa_type = resolve_type(col, self._TYPE_MAP)
                if sa_type.startswith("java."):
                    needed_imports.add(sa_type.rsplit(".", 1)[0])

        if needed_imports:
            needed_imports.discard("java.time")  # Already imported
            needed_imports.discard("java.util")  # Already imported
            for imp in sorted(needed_imports):
                parts.append(f"import {imp}")

        if needed_imports:
            parts.append("")

        for table in schema.tables:
            parts.append(self._generate_case_class(table))

        return "\n".join(parts)

    def _generate_case_class(self, table) -> str:
        """Generate a single case class."""
        class_name = self._to_pascal(table.name)
        lines: list[str] = []
        lines.append(f"case class {class_name}(")

        field_lines: list[str] = []
        for col in table.columns:
            field_lines.append(f"    {self._field_def(col)},")

        if field_lines:
            lines.append("\n".join(field_lines))
        else:
            lines.append("    // No fields")

        lines.append(")")

        return "\n".join(lines)

    def _field_def(self, col: Column) -> str:
        """Generate a case class field definition."""
        sa_type = resolve_type(col, self._TYPE_MAP)

        # Handle nullable → Option[T]
        scala_type = f"Option[{sa_type}]" if col.nullable else sa_type

        # Default value
        default_str = ""
        if col.default is not None:
            if isinstance(col.default, bool):
                default_str = f" = {str(col.default).lower()}"
            elif isinstance(col.default, str) and col.default.startswith("fn:"):
                fn_val = col.default[3:]
                fn_upper = fn_val.upper().rstrip("()")
                if fn_upper in ("CURRENT_TIMESTAMP", "NOW", "INSTANT_NOW"):
                    default_str = " = java.time.Instant.now()"
                elif fn_upper == "CURRENT_DATE":
                    default_str = " = java.time.LocalDate.now()"
                elif fn_upper == "UUID" or fn_upper == "RANDOM_UUID":
                    default_str = " = java.util.UUID.randomUUID()"
            elif isinstance(col.default, str):
                default_str = f' = "{col.default}"'
            elif isinstance(col.default, int | float):
                default_str = f" = {col.default}"

        return f"{col.name}: {scala_type}{default_str}"

    def _to_pascal(self, name: str) -> str:
        """Convert snake_case to PascalCase."""
        parts = name.split("_")
        return "".join(p.capitalize() for p in parts if p)
